spring:
  main:
    allow-bean-definition-overriding: true
server:
  servlet:
    context-path: /ces
#mybatis:
#  configuration:
#    database-id: ${mybatis.database.provider.type:mysql}
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

security:
  oauth2:
    client:
      permits: /login**,/admin/VerifyUserPassword,/admin/getUser,/api/**,/swagger**

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)